# SPDX-FileCopyrightText: 2025 FreshlyBakedCake
#
# SPDX-License-Identifier: MIT

name: Update npins dependencies
# This is inspired by https://github.com/getchoo/update-npins - though I wrote it from scratch
# I'm not using it as I need to run the npins command in a shell

on:
  schedule:
  - cron: "48 02 * * *" # Time is pretty arbitrary - the only important thing is that it's unlikely to be a peak time...

  workflow_dispatch:

jobs:
  update-npins:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub token for RoboPâtissière
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.CUSTOM_GITHUB_APP_ID }}
          private-key: ${{ secrets.CUSTOM_GITHUB_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
        with:
          extra_nix_config: "experimental-features = nix-command"

      - run: cd $GITHUB_WORKSPACE

      - name: Set up a cachix cache
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad
        with:
          # Name of a cachix cache to push and pull/substitute
          name: "freshlybakedcake"
          authToken: "${{ secrets.CACHIX_TOKEN }}"

      - name: Run npins update
        run: nix-shell ./nilla.nix -A shells.default.result.x86_64-linux --run 'npins update'

      - name: Create a pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        id: pull-request
        with:
          branch: auto/update-npins
          commit-message: "chore: bump npins dependencies"
          token: ${{ steps.generate-token.outputs.token }}
          title: "chore: bump npins dependencies"
          author: "RoboPâtissière[bot] <213641064+robopatissiere[bot]@users.noreply.github.com>"
          committer: "RoboPâtissière[bot] <213641064+robopatissiere[bot]@users.noreply.github.com>"
          body: |
            This is an automated npins dependency bump

      - if: steps.pull-request.outputs.pull-request-operation == 'created'
        name: Automerge pull request
        run: gh pr merge --rebase --auto "${{ steps.pull-request.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
